#!/bin/bash

# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

# From here down it all should be automatic

python "${OPENSHIFT_REPO_DIR}${DJANGO_MANAGE_PATH}" migrate --noinput;
python "${OPENSHIFT_REPO_DIR}${DJANGO_MANAGE_PATH}" collectstatic --noinput;