#!/bin/bash

# This is a simple script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the build step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

if [ -z ${DJANGO_MANAGE_PATH+x} ];

    then echo "ERROR: Environment variable DJANGO_MANAGE_PATH is not set."

fi

if [ -z ${DJANGO_PROJECT_CONFIG_PATH+x} ];

    then echo "ERROR: Environment variable DJANGO_PROJECT_CONFIG_PATH is not set."

fi

if [ -z ${OPENSHIFT_PYTHON_WSGI_APPLICATION+x} ];

    then echo "ERROR: Environment variable OPENSHIFT_PYTHON_WSGI_APPLICATION is not set."

fi

if [ -z ${OPENSHIFT_PYTHON_REQUIREMENTS_PATH+x} ];

    then echo "ERROR: Environment variable OPENSHIFT_PYTHON_REQUIREMENTS_PATH is not set."

fi