#!/bin/bash

# This is a simple script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the build step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

# Project name
export DJANGO_PROJECT_NAME='mysite';

# Pipeline
export DJANGO_PROJECT_PIPELINE_ENVIRONMENT='development'

# Virtual Env location
export OPENSHIFT_PYTHON_VIRTUAL_ENVIRONMENT="${OPENSHIFT_PYTHON_DIR}/virtenv/venv/"

# Django WSGI
export OPENSHIFT_PYTHON_WSGI_APPLICATION="${DJANGO_PROJECT_NAME}/${DJANGO_PROJECT_NAME}/wsgi.py";

# Pip requirements file location
export OPENSHIFT_PYTHON_REQUIREMENTS_PATH="${DJANGO_PROJECT_NAME}/requirements/${DJANGO_PROJECT_PIPELINE_ENVIRONMENT}.txt";
